### ISSUE TITLE
Can't fork?

### ISSUE THREAD

**Issue by palermog** [sunbliss/photorama#17]
I tried forking the repo, but all that comes with is the README. Am I doing something wrong?

**Comment by sunbliss** [comment]
@palermog Hi, please try to download the latest version from this link https://github.com/sunbliss/photorama/archive/v2.2.zip
Let me know if it worked.

**Comment by rastiazul** [comment]
the demo doesnt work

**Comment by sunbliss** [comment]
@rastiazul It's working now.
