### ISSUE TITLE
Could you please help me explain how to set up the navigation bar？

### ISSUE THREAD

**Issue by songxycc** [sunbliss/photorama#25]
I don't know in which file I can change the navigation bar，and how can I make the homepage display scroll without a VPN? Thanks!

**Comment by sunbliss** [comment]
@songxycc Which parts you want them to be changed?

**Comment by songxycc** [comment]
I wanna change the "GALLERY JOURNAL ABOUT" in the homepage , and the images in the homepage won’t display scroll  without a VPN，and the background is completely black.

**Comment by sunbliss** [comment]
@songxycc The homepeage does not include scrolling function. This is why I recommend adding the photos in landscape orientation.
As for the navigation bar, firstly go to _config.yml at https://github.com/sunbliss/photorama/blob/gh-pages/_config.yml#L34 and change the already listed items and if you need more, add them here.
Then, change the names of the corresponding folders (gallery, journal,about and any other you might add) to your items.
Lastly, you must change these item names inside the index files of the above folders and you will be fine.
