### ISSUE TITLE
the photo effect in gallery didn't work.

### ISSUE THREAD

**Issue by larrywhy** [sunbliss/photorama#4]
Hi, thanks for performing  a wonderful jekyll theme.

I already forked the git repo and replaced the BASEURL and  URL.

But the photo's effect didn't work. Would you help to check this issue?

The blog URL: http://larrywhy.github.io/photorama

It looks some CSS or js are not loaded.

**Comment by sunbliss** [comment]
Hi
I fixed the lines in the code that were causing the problem.
Please reupload this file https://github.com/sunbliss/photorama/blob/gh-pages/gallery/index.html and let me know if you still can't get the effect work.

**Comment by larrywhy** [comment]
the new URL is : http://larrywhy.github.io/why-photo
it looks like the slide effect in gallery page did't work.(it will directly open the image without using slide)
e.g. => https://larrywhy.github.io/why-photo/gallery/gallery02/

**Comment by sunbliss** [comment]
@larrywhy Ok, I am on it. I will get back to you as soon as possible.

**Comment by sunbliss** [comment]
@larrywhy Hi 
I have polished the template. Hopefully, there are no issues with the slider anymore. 
Please fork the template from [PHOTOR](https://github.com/sunbliss/photor) and let me know if everything works properly. 
If you are satisfied, I would appreciate it if you give me feedback, so I can upload the theme in its original source with the appropriate credits and some useful info about the image size.
Thank you

**Comment by larrywhy** [comment]
Hi, sunbliss
It looks fine now. Everything is awesome! 
May I ask why the "Search" page is removed in "PHOTOR" ? 
I think that is a useful function.
Thanks

**Comment by sunbliss** [comment]
@larrywhy The **SEARCH** page has been replaced by "Super Search" overlay from [Chinchang](https://github.com/chinchang/super-search). 

You can access it through the _search **icon**_ at the top right of every page, except for the home page. 

I thought it is more functional this way and there are still all the tags and the categories clouds at the bottom of every post. 

Unless you find any problem concerning the new search function, I shall close this issue.
